# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  build-sfu-ami:
    parameters:
      packer_version:
        type: string
        description: Packer linux amd64 version to use
        default: 1.9.4
      kubernetes_version:
        type: string
        description: The EKS version we're building against
      kubernetes_build_date:
        type: string
        description: Date is the set as a path to the s3 repository
      instance_type:
        type: string
        description: The instance type to build against
      ami_preffix:
        type: string
        description: The AMI prefix that will be used, the suffix is the commit shorthash
      ami_architecture:
        type: string
        description: Which architecture are we building against? x86_64
        default: x86_64
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run:
          name: install required packages
          command: |
            sudo apt-get install build-essential unzip -y
            cd /tmp && \
            curl -LO https://releases.hashicorp.com/packer/<<parameters.packer_version>>/packer_<<parameters.packer_version>>_linux_amd64.zip && \
            unzip packer_<<parameters.packer_version>>_linux_amd64.zip && \
            sudo mv packer /usr/bin && \
            rm packer_<<parameters.packer_version>>_linux_amd64.zip
            packer version
            packer plugins install github.com/hashicorp/amazon
      - run:
          name: create SFU EKS AMI using packer
          command: |
            export USER="CircleCI"
            make k8s kubernetes_version=<<parameters.kubernetes_version>> \
                     kubernetes_build_date=<<parameters.kubernetes_build_date>> \
                     arch=<<parameters.ami_architecture>> \
                     ami_name=<<parameters.ami_preffix>>-<<parameters.kubernetes_version>>-${CIRCLE_SHA1:0:9} \
                     instance_type=<<parameters.instance_type>>

workflows:
  build:
    jobs:
      - build-sfu-ami:
          kubernetes_version: "1.24.16"
          kubernetes_build_date: "2023-08-16"
          instance_type: c6a.xlarge
          ami_preffix: gather-sfu-eks
          filters:
            branches:
              only:
                - main
                - staging
